### ISSUE TITLE
Allow a fresh checkout to run easily

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/pod#86]
Allow a newly checkout repo to "just work" locally and make it easy for new devs to run the test suite. Make sure running tests is convenient and stable.

## Tasks
- [ ] scripts store stuff outside of project (e.g. `cp: cannot stat '/home/vagrant/Library/Ethereum/8383/keystore/migrateAccount.json': Permission denied`)
- [ ] scripts check out stuff outside of go-centrifuge folder (`centrifuge-ethereum-contracts`)
- [ ] when running as mining, the CPU usage goes up to 190%. Kills battery. Burns legs.

### General

- Fix readme up
- Test execution on clean checkout should be easy - to verify if "everything is in the right spot"
- anything else...

###  ./scripts/test_wrapper.sh
Just tried to run integration tests locally. It seems like the README doesn't mention anything about having to run `test_wrapper.sh` with the `migrate` flag but it seems like I need to run that manually.

```
# 1st attempt:
./scripts/test_wrapper.sh 
# fails because local.json is not found
...
up to date in 0.299s
cat: /home/vagrant/work/cent-go/src/github.com/CentrifugeInc/centrifuge-ethereum-contracts/deployments/local.json: No such file or directory
printf: usage: printf [-v var] format [arguments]
cat: /home/vagrant/work/cent-go/src/github.com/CentrifugeInc/centrifuge-ethereum-contracts/deployments/local.json: No such file or directory
printf: usage: printf [-v var] format [arguments]
cat: /home/vagrant/work/cent-go/src/github.com/CentrifugeInc/centrifuge-ethereum-contracts/deployments/local.json: No such file or directory
printf: usage: printf [-v var] format [arguments]
...
# 2nd attempt:
./scripts/test_wrapper.sh migrate
# fails because: 
./scripts/migrate.sh: line 30: truffle: command not found

# 3rd attempt:
npm install -g truffle
./scripts/test_wrapper.sh migrate
```

Writing this down because I think we should discuss how we can improve the usability of our scripts and make our test setup run quicker. Right now docker is using a solid 190% of my CPU. 

Could we implement testgeth/ganache for running simpler integration tests and then only run functional tests against a well defined setup?
